# Generated by Django 4.0.2 on 2022-02-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('HR', 'HR'), ('Dr', 'Dr'), ('Nurse', 'Nurse'), ('Ph', 'Ph')], default='None', max_length=20)),
                ('expeience', models.IntegerField(default=0)),
                ('start_time', models.TimeField(default='00:00:00')),
                ('end_time', models.TimeField(default='00:00:00')),
                ('degree', models.CharField(choices=[('PH', 'PH'), ('colleague', 'colleague'), ('Master', 'Master'), ('Graduated', 'Graduated')], default='None', max_length=20)),
            ],
        ),
    ]
