# Generated by Django 4.0.2 on 2022-02-13 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_personal_id_myuser_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(default=0)),
                ('blood_pressure_up', models.IntegerField(default=0)),
                ('blood_pressure_down', models.IntegerField(default=0)),
                ('respiration_rate', models.IntegerField(default=0)),
                ('temprature', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=7)),
                ('first_name', models.CharField(default='first_name', max_length=20)),
                ('last_name', models.CharField(default='last_name', max_length=20)),
                ('weigth', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('heigth', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('marital_status', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced')], default='Ba2s', max_length=8)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='Non', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
